application:
  port: 8000
database: 
  host: "localhost"
  port: 15432
  username: "ztopApp"
  password: "ztopPa55word"
  database_name: "ztop"
email_client:
  base_url: "localhost"
  sender_email: "test@bts.org"
  authorization_token: "test-secret-token"